name: datagrid_example
description: This project demonstrates how to use Syncfusion Flutter DataGrid widget?.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_datagrid: ^18.2.44-beta
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
